### ISSUE TITLE
Hosting on cdnjs

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/iiifviewer#14]
Is it possible to host iiifviewer builds on cdnjs? https://cdnjs.com/ Do we need versions? We are using it in projects and their linking build on gh-pages

**Comment by klokan** [comment]
Feel free to make this happen @daliborjanak

We should make releases of the viewer anyway.

In case authoritative registration is required we should use sysadmin@ email (or github account).

**Comment by daliborjanak** [comment]
For CDNJS:
- We need add license and create NPM package
- then [request via ticket](https://goo.gl/0pRcOk) or create pull request to cdnjs repository (12Gb unpacked).

But they may not accept our release because they accepting only popular projects (eg. we need more stars):

"[Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.](https://github.com/cdnjs/cdnjs)"

So i thing it's impossible yet. I created only release (with verson discused with @petrsloup )

But most of our projects (eg IIIFServer) still uses link to gh-pages. It's not good.

**Comment by daliborjanak** [comment]
www.iiifserver.com/iiifviewer/1.0.0/iiifviewer-min.js

**Comment by petrsloup** [comment]
The library is now hosted at:
https://cdn.klokantech.com/iiifviewer/v1.1/iiifviewer.js
https://cdn.klokantech.com/iiifviewer/v1.1/ol-iiifviewer.js
`v1.0` is also available + `v1` alias for the latest `v1.x` release.

See https://github.com/klokantech/cdn.klokantech.com for details.
