### ISSUE TITLE
Some parts of images missing in IE10&9

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/iiifviewer#17]
I created an example for NLS in http://labs.klokantech.com/nls/viewer/. I tested it in IE. V11 works OK, but 10 and 9 sometimes didn't display part of images on bottom border. It hapened ramdomly on different  zoomlevels. See screenshots:

![image](https://cloud.githubusercontent.com/assets/1891090/17103215/a1d6e35a-527d-11e6-8e34-b084430716e5.png)

![image](https://cloud.githubusercontent.com/assets/1891090/17103255/c1e28ad2-527d-11e6-9e0c-c4322b39dca4.png)

If I reload the window that the previous missing images were there. I tried 3 different machines but all with this same problem.

**Comment by petrsloup** [comment]
This might be related to https://stackoverflow.com/questions/16192332/internet-explorer-9-sometimes-draws-blank-images-on-canvas.

I am no longer to reproduce this issue in v1.2 (probably solved by some change in OpenLayers in the last year). I'm closing this ticket.
