### ISSUE TITLE
Print to PDF (client side)

### ISSUE THREAD

**Issue by klokan** [klokantech/iiifviewer#2]
Similar to:
http://gingerik.github.io/ol3/examples/export-pdf.html

But - it renders to external (invisible canvas).
Clean code in a branch of iiifviewer.

Print the visible bounds so it fits to page.
It should run with IIIF but also other sources (first version can always expect pixel coordinates.

Ideal - title / url / copyright notice / logo overlay in corners.

**Comment by klokan** [comment]
Reported by NLS as not functioning in IE (9-11)

**Comment by klokan** [comment]
Possible workaround made with Downloadify for IE.

**Comment by clientportal** [comment]
FROM:nls
Petr / Dalibor,

Thank you for re-opening this. I didn't realise when I asked yesterday, that the PDF download is actually working okay in IE for your original implementation - ie. http://geo.nls.uk/maps/dev/iiifviewer/index.html - but just not with the NLS CSS, ie 
http://labs.klokantech.com/nls/iiifviewer/iiifviewer.html

**Comment by klokan** [comment]
The bug for IE print is probably related to CSS. We are examining...

**Comment by klokan** [comment]
I tested IE9 and I am getting security error on getImageData even on the example http://klokantech.github.io/iiifviewer/examples/print.html - but this may be related to implementation of the CANVAS in IE9.
IE 11 runs fine.

We are back in the fact, that only reliable and always running print implementation without limits is to be done on the server: https://github.com/klokan/gr4/issues/118
