### ISSUE TITLE
How to integrate IIIF viewer instead of using default iiif viewer?

### ISSUE THREAD

**Issue by malik-umair** [klokantech/iiifviewer#20]
Hi, I need to know how can I use iiif viewers like IIPMooViewer, Mirador or Universal Viewer if I purchase iiif hosting? I've asked this question via email on your contact page but didn't received any response so I'm writing here. I'm planing to use iiif hosting but I don't know the process how can I use above mentioned viewer in your hosting, will you people set it up for me or I have to do it myself? Also how can I add other functionalities in your viewer like rotate and other which  these viewer provide, as your default viewer just provide zoom in/out functionality.

**Comment by petrsloup** [comment]
The IIIFHosting provides standard `info.json` (http://iiif.io/api/image/), which can be used directly in many different viewers. You can find documentation on how to use it in the documentation of the individual viewers.

(This issue does not belong here, but I've created an internal ticket on IIIFHosting to improve documentation to make this more clear.)
