### ISSUE TITLE
IIIFViewer problem using Safari on Mac

### ISSUE THREAD

**Issue by clientportal** [klokantech/iiifviewer#33]
FROM:martin.mikita@klokantech.com	Martin Mikita
Hello Klokan Team,

We have reports from two users that our IIIF viewer, based on yours at http://klokantech.github.io/iiifviewer/ is only displaying part of the image in Safari browsers on the Mac.

I am attaching an image of the NLS problem, and the Klokantech IIIFViewer problem.

I hope that this is something you can look into and advise us on. We've found it difficult to replicate the error through emulation, and don't have direct access to Safari on a Mac here.

 

Many thanks,

Chris
---
Chris Fleet
Map Curator | Collections and Research Department 

Link to the Clientportal:
https://clientportal.klokantech.com/iiifviewer/issues/33

**Comment by clientportal** [comment]
FROM:martin.mikita@klokantech.com	Martin Mikita
Attached file:
![IIIFViewer1.png](http://clientportal.klokantech.com/uploads/1de8ee69bae816ddee55c056a0d99984/IIIFViewer1.png)
Attached file:
![NLS-error1.png](http://clientportal.klokantech.com/uploads/1de8ee69bae816ddee55c056a0d99984/NLS-error1.png)

**Comment by petrsloup** [comment]
Hi, maintaining this project is no longer a priority for our team.

I can recommend using OpenLayers instead, which now has support for IIIF out of the box:
https://openlayers.org/en/master/examples/iiif.html

It's going to be part of the v6.0.0, which is going to be released hopefully soon.

**Comment by clientportal** [comment]
FROM:c.fleet@nls.uk	Chris Fleet
Hi Petr,

That's very helpful to hear. I hadn't seen the IIIF example in OpenLayers, so this is helpful, as well as your plans to stop supporting http://klokantech.github.io/iiifviewer/ 

Thanks for letting me know, and I'm very happy for you to close this issue.

Chris

**Comment by clientportal** [comment]
FROM:c.fleet@nls.uk	Chris Fleet
Hello again Petr,

Do you happen to know when OpenLayers v6 will be released? 

Thanks,

Chris

**Comment by petrsloup** [comment]
Sorry, I don't have information about that. But I'm hoping it will be very soon...
