### ISSUE TITLE
Permalink example

### ISSUE THREAD

**Issue by klokan** [klokantech/iiifviewer#4]
The viewer should support permalink for the viewed position on the map, for easier copy&paste of URLs.

The first implementation could probably follow the OL2 syntax of the permalink (with a hash), to mimic the NLS viewer: http://maps.nls.uk/view/74479823#zoom=3&lat=5800&lon=8486&layers=BT

For implementation hits see "Permalink" section of the blog post:
http://oobrien.com/2015/01/openlayers-3-and-datashine/

BTW an ideal full viewer example would include also the Overview Control as in NLS viewer (http://openlayers.org/en/v3.1.1/examples/overviewmap-custom.html)

**Comment by clientportal** [comment]
FROM:nls
Hello Petr / Dalibor,

Just in case its helpful, we have implemented the OL2-style Permalinks at:
http://geo.nls.uk/maps/dev/ol3/explore/#zoom=6&lat=53.5689&lon=-0.7531&layers=10 

You will find it very easy - much easier than me, and just involves the stages outlined at: 
http://oobrien.com/2015/01/openlayers-3-and-datashine/  ...and given the NLS URLs layers=BT, the ol3 syntax is along these lines:

function updateUrl()  
{
	var centre = ol.proj.transform(map.getView().getCenter(), "EPSG:3857", "EPSG:4326");
	window.location.hash = "zoom=" + map.getView().getZoom()  + "&lat=" + centre[1].toFixed(4)  + "&lon=" + centre[0].toFixed(4) +  "&layers=BT" ; 
}

It would be great if you can prioritise this - hoping it is quick? We have ongoing complaints about the difficulties of printing screengrabs with the current viewer.

Thanks,

Chris

**Comment by daliborjanak** [comment]
Implemented. Please look at example:
http://klokantech.github.io/iiifviewer/examples/permalink.html

**Comment by clientportal** [comment]
FROM:nls
Many thanks, Dalibor - this is perfect and exactly what we were hoping for.

To finish, please could you develop a version with the overlaywindow as at: http://openlayers.org/en/v3.1.1/examples/overviewmap-custom.html - hopefully we can customise to look as: http://maps.nls.uk/view/00000207 

Your brief advice too on how we merge the existing http://klokantech.github.io/iiifviewer/examples/permalink.html and http://klokantech.github.io/iiifviewer/examples/print.html would be appreciated too - they use different iiifviewer js files, but can/will these be merged? Ideally we would like to deploy a single viewer.js file, but more is okay if necessary.

thanks!

**Comment by clientportal** [comment]
FROM:nls
Hello again Dalibor,

With apologies, I only managed to try deploying your Permalink example today for the NLS viewer at:
http://geo.nls.uk/maps/dev/iiifviewer/207_iiifviewer_permalink.html

All is fine, apart from for the lat= variable that is negative from the top down, but is currently positive, from the bottom up - ie. http://maps.nls.uk/view/00000197#zoom=2&lat=2109&lon=5746&layers=BT 
I hope this is easy and quick to fix for us?

I also tried implementing your Print to PDF which worked fine as your demo had it at: http://geo.nls.uk/maps/dev/iiifviewer/print.html but produces an error in line 224 of 	
iiifviewer-pdf.js when I try to integrate it with the current NLS css, etc. at: http://geo.nls.uk/maps/dev/iiifviewer/207_iiifviewer.html (Print tab lower left). Maybe this is my 'Chris the Hacker' coding (as Petr would say), but very grateful for any advice.

**Comment by klokan** [comment]
Dalibor,
- [ ] all coordinates must be positive!
- [ ] raster coordinates (x/y) have the origin in the TOP-LEFT corner and grows down and to the right.
- [ ] Geo coordinates (lat/lng) have the origin in the BOTTOM-LEFT corner and grows up and to the right.
Verify on the example I have given you during the last Hangout, that the URL has exactly the same hash as NLS existing viewer for the sample image

Please provide Chris with a complete example, hosted on labs and downloadable as .zip - with all the requested features (permalink, overview window, print + sample CSS customisation).
Thanks!

**Comment by daliborjanak** [comment]
I finished last requirements with positive coordinates etc. yesterday. Results here: http://klokantech.github.io/iiifviewer/examples/permalink.html

For finalizing: I will prepare full example for you. We are now working on upgrade to Openlayers 3.2 which is necessary for using overview map and new ol features (it is not implemented in older relases).

Note: In pdf branch is IiifViewer with print to pdf. Printing is not in master. I merged all changes to pdf.

**Comment by daliborjanak** [comment]
I prepared full example. It's available at http://labs.klokantech.com/nls/iiifviewer/ and downloadable at http://labs.klokantech.com/nls/iiifviewer/nls-iiifviewer.zip .

There is function ```printDoc()``` which will print the document (In my example starts to run by pressing button in top-right corner). 

I customized look of overview map. Css is embed in html, you cen move it to file with other css. ol3.css is not necessary.

I also added nls logo to pdf document.

Let me know if it's ok.

**Comment by clientportal** [comment]
FROM:C.Fleet@nls.uk
Great, many thanks indeed Dalibor - at first glance, this looks great and just as we were hoping for!

I've downloaded it and it works fine just out of the box:

http://geo.nls.uk/maps/dev/iiifviewer/index.html 

and also changing the URL to the NLS IIPImage

http://geo.nls.uk/maps/dev/iiifviewer/207index.html 

...when I put it with the NLS CSS at

file:///N:/dev/iiifviewer/207_iiifviewer.html 


...it gives me a Javascript 'Error: Invalid element' in line 42 of ol-iiifviewer-pdf.js in Firebug. I tried switching to "http://klokantech.github.io/iiifviewer/iiifviewer-pdf.js" and it is the same.

I realise this must be in the NLS CSS or how I have put your viewer inside the NLS header and footer, so don't feel you need to fix it - your job was exactly as you have done it, to provide a clean and working viewer... but if you had any quick ideas, I'd be very grateful - I will ask Tony too.

Many thanks,

Chris

**Comment by daliborjanak** [comment]
I repired it: http://labs.klokantech.com/nls/iiifviewer/iiifviewer.html
It looks great. I also lunched printing (left bottom menu item).
I changed ```new IiifViewer('viewer', url, function() {``` in page to ```new IiifViewer('map', url, function() ``` (as first parameter of IiifViewer is name element when map is displayed)

You can download full example at http://labs.klokantech.com/nls/iiifviewer/iiifviewer-in-page.zip

**Comment by clientportal** [comment]
FROM:C.Fleet@nls.uk
Wow, you're a star, Dalibor! 

Thanks ever so much - all done and implemented, and yes - it looks really great!

**Comment by clientportal** [comment]
FROM:C.Fleet@nls.uk
Hello Dalibor,

Well, I know you thought this was done, but we have just have one query/problem which I hope will be quick to resolve. The printDoc() function generates a security error and no PDF in all the versions of Internet Explorer (versions 9-11) we have tried here. It works fine in Chrome and Firefox, but please can it be fixed so it works in IE?

Many thanks,

Chris

**Comment by klokan** [comment]
Problem with print is related to #2 - which is now reopened.

**Comment by klokan** [comment]
The tickets are starting to be very messy.
This ticket is about "Permalink" - only issues related to permalink is to be discussed here.
Issues related to print are to be discussed at #2.
Issues specific to the complete example for NLS are to be discussed under #7
