### ISSUE TITLE
Broken links to logo

### ISSUE THREAD

**Issue by klokan** [klokantech/iiifviewer#5]
See bottom left corner of http://klokantech.github.io/iiifviewer/

**Comment by daliborjanak** [comment]
Logos are now available on klokantech domain:
http://klokantech.com/img/klokantech.png
and horizontal:
http://klokantech.com/img/klokantech-h.png

**Comment by klokan** [comment]
Would it be better to put it to gh-pages to be independent of the other domain and also the load faster?
