### ISSUE TITLE
PDF print auto size

### ISSUE THREAD

**Issue by klokan** [klokantech/iiifviewer#8]
The PDF print to "auto" should use the size of the canvas element, not of the page.
Right now it seems to be using the size of page which is wrong.

It runs fine for the demo at http://klokantech.github.io/iiifviewer/examples/print.html, because there the canvas has a size of the page, but otherwise it is wrong.

**Comment by daliborjanak** [comment]
Size of element is passed to constructor of jsPdf and its created on instanceof IiifPrint. We can change behavior of creating instance of jsPdf or:
To constructor could be added element instead of "auto". IiifPrint will take size of this element...

**Comment by clientportal** [comment]
FROM:C.Fleet@nls.uk
Dalibor,

I'm extremely grateful for this further work, which is even better functionality than expected for the PDF output! We now have the best of both worlds - a logo and text, but a way of filling the page with the map too by altering the aspect ratio - perfect, thankyou! 

I have implemented this in NLS at: http://geo.nls.uk/maps/dev/iiifviewer/index.html 

I hate saying there is something else... but now our Web Administrator, Tony Stuart, does not like the use of the inline <style> CSS, ie. this section

<style>

      .ol-overviewmap {
        position: absolute;
        right: 0;
        bottom: 0;
        background-color: #fff;
      }
      .ol-overviewmap .ol-overviewmap-map {
        height: 150px;
        margin: 2px;
        width: 150px;
        display: inline-block;
      }
      .ol-overviewmap-box {border: 1px solid #ee0000;}
      .ol-overviewmap button{display: none;}
      .ol-zoom button{display:block;margin:1px;padding:0;color:#fff;font-size:20px;font-weight:700;text-decoration:none;text-align:center;height:1.375em;width:1.375em;line-height:.4em;background-color:#7b98bc;background-color:#003;border:none;}
      .ol-zoom button:hover{cursor: pointer;}
      .ol-zoom{position:absolute;}
      .ol-zoom{position: absolute; top: 100px; left:0;}
      .browseralert{position: absolute; top: 125px; left: 10px; display: block;}

</style>

When we move this to a separate CSS, the printing still works fine in Chrome and FF, but not in IE. Tony has asked me to ask you about this, as he says using inline CSS is bad practice, it doesn't cache and is best avoided.

If you think nothing can be done very easily, please just say so and I will tell him. But he is not keen to implement the <style> within the HTML if possible.

**Comment by klokan** [comment]
No need in the API is required. The PDF page is going to be initialised when first object is added.
