### ISSUE TITLE
Licence of iiifviewer

### ISSUE THREAD

**Issue by jacmendt** [klokantech/iiifviewer#9]
Does there exist an opensource licence for this software product?

**Comment by klokan** [comment]
See: https://github.com/klokantech/iiifviewer/blob/master/LICENSE.md

The license included now in the code repository is equal to OpenLayers3.
On the viewer specific code is copyright of Klokan Technologies - and the copyright must be preserved.
Link to http://www.klokantech.com is very welcome in the documentation and code.

**Comment by klokan** [comment]
BTW Greetings to Dresden, Jacob! ;-)

**Comment by jacmendt** [comment]
Thank you and i hope you are doing good.

**Comment by klokan** [comment]
BTW Where do you plan to use our IIIF viewer or the code from it?

**Comment by jacmendt** [comment]
Yet there are no concrete plans. I was testing a bit with the viewer to check out the IIIF. If we got more concrete plans i will give you known.
